<?php
    if(!empty($_POST)){
        $foto ='img/'.$_FILES['foto']['name'];
        move_uploaded_file(
            $_FILES['foto']['tmp_name'],
            dirname(__DIR__).'/'.$foto
        );

        extract($_POST);
        $arquivo = fopen(dirname(__DIR__).'/estoque.csv','a+');
        fwrite($arquivo,"{$nome};{$modelo};{$fabricante};{$categoria};{$quantidade};{$foto}".PHP_EOL);
        fclose($arquivo);
        echo "<div class='alert alert-success'>
                <strong>Cliente Cadastrado</strong> Com Sucesso !!!
        </div>";
    }
?>

<h1 class="text-center">Estoque</h1>
<hr>
    <section class="row">

        <div class="col-md-6 align-self-center">
            <img src="img/control_panel.svg" width="90%" alt="">
        </div>

        <div class="col-md-6">
            <article class="card card-body text-bg-primary">
                <form action="" method="post" enctype="multipart/form-data">

                            <label for="nome" class="form-label">Nome</label>
                                    <input name="nome" type="text" class="form-control mb-3"  placeholder="Nome do produto">
                            <label for="modelo" class="form-label">Modelo</label>
                                    <input name="modelo" type="text" class="form-control mb-3"  placeholder="Modelo do Produto">
                            <label for="fabricante" class="form-label">Fabricante</label>
                                    <input name="fabricante" type="text" class="form-control mb-3"  placeholder="Digite o Fabricante">
                            <label for="categoria" class="form-label">Categoria:</label>
                                <select name="categoria" class="form-select" aria-label="Default select example">
                                    <option selected>Selecione a Categoria</option>
                                    <option value="1">Novo</option>
                                    <option value="2">Usado</option>
                                    <option value="3">Em Manuteção</option>
                                </select>
                                <label for="quantidade" class="form-label">Quantidade</label>
                                    <input name="quantidade" type="number" class="form-control mb-3"  placeholder="Digite o Fabricante">

                            <label  for="foto">Foto</label>
                                    <input name="foto" type="file" class="form-control mb-3">    

                            <div class="d-grid">
                                    <button class="btn btn-outline-light btn-lg ">Cadastrar Produto</button>
                            </div>
                </form>
            </article>
        </div>
    </section>