<h3 class="text-center">Editar Veiculo</h3>
<hr>
    <section class="row">

        <div class="col-md-6 align-self-center">
            <img src="img/control_panel.svg" width="90%" alt="">
        </div>

        <div class="col-md-6">
            <article class="card card-body text-bg-primary">
                <form action="" method="post" enctype="multipart/form-data">
                        
                            <label for="placa" class="form-label">Placa</label>
                                    <input name="placa" type="text" class="form-control mb-3"  value="<?=$veiculosEditar[0];?>" >
                            <label for="renavam" class="form-label">Renavam</label>
                                    <input name="renavam" type="text" class="form-control mb-3"  value="<?=$veiculosEditar[1];?>">
                            <label for="modelo" class="form-label">Modelo</label>
                                    <input name="modelo" type="text" class="form-control mb-3"  value="<?=$veiculosEditar[2];?>">
                            <label for="estado" class="form-label">Estado</label>
                                <select name="estado" class="form-select" aria-label="Default select example">

                                    <?php                                         
                                         if($veiculosEditar[3]==1){
                                            $veiculosEditar[3]='Novo';
                                         }else if($veiculosEditar[3]==2){
                                            $veiculosEditar[3]='Usado';
                                         }
                                    ?>

                                    <option selected><?= $veiculosEditar[3];?></option>
                                    <option value="1">Novo</option>
                                    <option value="2">Usado</option>
                                    
                                </select>
                            <label  for="foto">Foto</label>
                                    <input name="foto" type="file" class="form-control mb-3"">    

                            <div class="d-grid">
                                    <button class="btn btn-outline-light btn-lg ">Atualiza Veiculo</button>
                            </div>
                </form>
            </article>
        </div>
    </section>