<h1 class="text-center">Editar de Estoque</h1>
<hr>
    <section class="row">

        <div class="col-md-6 align-self-center">
            <img src="img/control_panel.svg" width="90%" alt="">
        </div>

        <div class="col-md-6">
            <article class="card card-body text-bg-primary">
                <form action="" method="post" enctype="multipart/form-data">
                        
                            <label for="nome" class="form-label">Nome</label>
                                    <input name="nome" type="text" class="form-control mb-3"  value="<?=$estoqueEditar[0];?>" >
                            <label for="modelo" class="form-label">Modelo</label>
                                    <input name="modelo" type="text" class="form-control mb-3"  value="<?=$estoqueEditar[1];?>">
                            <label for="fabricante" class="form-label">Fabricante</label>
                                    <input name="fabricante" type="text" class="form-control mb-3"  value="<?=$estoqueEditar[2];?>">
                            <label for="categoria" class="form-label">Categoria:</label>
                                <select name="categoria" class="form-select" aria-label="Default select example">

                                    <?php                                         
                                         if($estoqueEditar[3]==1){
                                            $estoqueEditar[3]='Novo';
                                         }else if($estoqueEditar[3]==2){
                                            $estoqueEditar[3]='Usado';
                                         }else{
                                            $estoqueEditar[3]='Em Manutenção';
                                         }
                                    ?>

                                    <option selected><?= $estoqueEditar[3];?></option>
                                    <option value="1">Novo</option>
                                    <option value="2">Usado</option>
                                    <option value="3">Em Manutenção</option>
                                </select>
                            <label for="quantidade" class="form-label">Fabricante</label>
                                    <input name="quantidade" type="text" class="form-control mb-3"  value="<?=$estoqueEditar[4];?>">                

                            <label  for="foto">Foto</label>
                                    <input name="foto" type="file" class="form-control mb-3"">    

                            <div class="d-grid">
                                    <button class="btn btn-outline-light btn-lg ">Atualiza Produto</button>
                            </div>
                </form>
            </article>
        </div>
    </section>