<?php
    $bebidas = file(__DIR__.'/../bebidas.csv');
?>

<h1>Pagina de Listagem</h1>

<table class="table table-hover table-striped">
    <thead class="table-dark">
        <tr>
            <th>Título</th>
            <th>Descrição</th>
            <th>Preço</th>
            <th>Quantidade</th>
            <th>Foto</th>
            <th>Ações</th>
        </tr>
    </thead>
    <tbody>
        <?php
        foreach($bebidas as $cadaLinha){
            $cadaBebida = explode(';',$cadaLinha);
            echo "
            <tr>
                <td>{$cadaBebida[0]}</td>
                <td>{$cadaBebida[1]}</td>
                <td>{$cadaBebida[2]}</td>
                <td>{$cadaBebida[3]}</td>
                <td><img width='50px' scr='{$cadaBebida[4]}'></td>
                <td>
                    <a href='#' class='btn btn-primary'>adicionar</a>
                    <a href='#' class='btn btn-danger'>remover</a>
                </td>
            </tr>
            ";
        }

        ?>

        
    </tbody>
</table>