<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
   
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <title>Consumo de Bebidas</title>
</head>
<body class="container justify-content-center">
    <div class="col-md-6 offset-md-3 mt-5">
        <canvas class="justify-content-center"  id="myChart"></canvas>
      </div>    
</body>

<script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
<script> 
const data = {
  labels: [
    'Maxwell',
    'Alessandro',
    'Jacques',
    'Wagner',
    'Robson',
    'Laerte',
    'Cecilia'
  ],
  datasets: [{
    label: 'Consumo de Bebidas',
    data: [7, 30, 15, 25, 10,25,5],
    backgroundColor: [
      'rgb(255, 99, 132)',
      'green',      
      'rgb(255, 205, 86)',      
      'rgb(54, 162, 235)',
      'blue',
      'red',
      'purple'

    ],
    hoverOffset: 30
  }]
};
  
const config = {
  type: 'pie',
  data: data,
  radius:30,
};
  </script>

<script>
    const myChart = new Chart(
      document.getElementById('myChart'),
      config
    );
  </script>
</html>