<nav class="mt-5">      
            <div class="dropdown d-line">
            <a href="/" class="btn btn-outline-dark">Inicio</a>
            <a href="/nova-bebida" class="btn btn-outline-dark">Nova Bebida</a>
            <a href="/listar-bebidas" class="btn btn-outline-dark">Listar Bebidas</a>

            <button class="btn btn-outline-dark dropdown-toggle" type="button" id="dropdownMenuButton1" data-bs-toggle="dropdown" aria-expanded="false">
                        Categorias
            </button>
                        <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton1">
                                <li><a class="dropdown-item" href="/categorias/adicionar">Adicionar</a></li>
                                <li><a class="dropdown-item" href="/categorias/listar">Listar</a></li>
                        </ul>            
  </ul>
</div>
    <hr>  