<?php 
if(!empty($_POST)){

    $foto = 'img/'.$_FILES['foto']['name'];

    move_uploaded_file(
        $_FILES['foto']['tmp_name'],
        dirname(__DIR__,3).'/public/'.$foto
    );

   // var_dump($_FILES);
    
   /* $titulo = $_POST['titulo'];
    $descricao = $_POST['descricao'];
    $preco = $_POST['preco'];
    $quantidade = $_POST['quantidade'];
    $foto = $_POST['foto'];
    */
     extract($_POST);
     $arquivo = openFile();
     fwrite($arquivo,"{$titulo};{$descricao};{$preco};{$quantidade};{$foto}".PHP_EOL);
     fclose($arquivo);
     WebNotification::add('Bebida adicionada');
     }
?>

<h1 class="te">Pagina de cadastro</h1>

<section class="row">
    <div class="col">
      <img width="90%" src="img/add.svg" alt="">

    </div>

    <div class="col">
        <article class=" card card-body text-bg-dark">

        <form action="" method="post" enctype="multipart/form-data">
            <label for="titulo">Título</label>
                <input name="titulo" type="text" class="form-control mb-3">
            <label for="descricao">Descrição</label>
                <input  name="descricao" type="text" class="form-control mb-3"">    
            <label for="preco">Preço</label>
                <input name="preco" type="number" step="0.01" class="form-control mb-3"">    
            <label for="quantidade">Quantidade</label>
                <input name="quantidade" min="0" type="number" class="form-control mb-3"">

            <label  for="foto">Foto</label>
                <input name="foto" type="file" class="form-control mb-3"">

               <div class="d-grid">
                     <button class="btn btn-outline-light btn-lg ">Salvar</button>
               </div>

        </form>

        </article>

    </div>
</section>