<?php
$id = $_GET['id'];

$bebidas =  loadFile();

$bebidaParaEditar = explode(';', $bebidas[$id]);
    if(!empty($_POST)){
        $bebidaParaEditar[0] = $_POST['titulo'];
        $bebidaParaEditar[1] = $_POST['descricao'];
        $bebidaParaEditar[2] = $_POST['preco'];
        $bebidaParaEditar[3] = $_POST['quantidade'];
        
        $bebidas[$id] = implode(';',$bebidaParaEditar);

        //excluindo arquivo
        removeFile();

        $novoArquivo = openFile();
        foreach($bebidas as $cadaBebida){
            fwrite($novoArquivo,$cadaBebida);
}
fclose($novoArquivo);

echo "<div class='alert alert-success'>
    Pronto!! Bebida Cadastrada
</div>";
    }
 
render('bebidas/form_edit',[
    'bebidaParaEditar' => $bebidaParaEditar,
]);
    
//include dirname(__DIR__).'/paginas/form_edit.phtml';

