<h1 class="te">edição de cadastro</h1>

<section class="row">
    <div class="col">
      <img width="90%" src="img/add.svg" alt="">

    </div>

        <?php
            foreach($bebidaParaEditar as $bebida){

            }
        ?>

    <div class="col">
        <article class=" card card-body text-bg-dark">

        <form action="" method="post" enctype="multipart/form-data">
            <label for="titulo">Título</label>
                <input value="<?=$bebida->titulo;?>" name="titulo" type="text" class="form-control mb-3">
            <label for="descricao">Descrição</label>
                <input value="<?=$bebida->descricao;?>"  name="descricao" type="text" class="form-control mb-3"">    
            <label for="preco">Preço</label>
                <input value="<?=$bebida->preco;?>" name="preco" type="number" step="0.01" class="form-control mb-3"">    
            <label for="quantidade">Quantidade</label>
                <input value="<?=$bebida->quantidade;?>" name="quantidade" min="0" type="number" class="form-control mb-3"">

            <label  for="foto">Foto</label>
                <input name="foto" type="file" class="form-control mb-3"">

               <div class="d-grid">
                     <button class="btn btn-outline-light btn-lg ">Salvar</button>
               </div>

        </form>

        </article>

    </div>
</section>