
<h3 class="text-center mb-5">Listagem de Bebidas</h3>

<table class="table table-hover table-striped">
    <thead class="table-dark">
        <tr>
            <th>Título</th>
            <th>Descrição</th>
            <th>Preço</th>
            <th>Quantidade</th>
            <th>Foto</th>
            <th>Ações</th>
        </tr>
    </thead>
    <tbody>
        <?php
        foreach($bebidas as $cadaBebida){                     
            echo "
            <tr>
                <td>{$cadaBebida->titulo}</td>
                <td>{$cadaBebida->descricao}</td>
                <td>{$cadaBebida->preco}</td>
                <td>{$cadaBebida->quantidade}</td>
                <td>
                    <a onclick=abrirFoto(this) data-image='/../$cadaBebida->foto' href='#' data-bs-toggle='modal' data-bs-target='#abrirFoto'>
                         <img width='50px' src='/../{$cadaBebida->foto}'>
                    </a>
                </td>
                <td>
                    <a href='/bebidas/editar?id={$cadaBebida->id}' class='btn btn-primary'>Editar</a>                    
                    <a class='btn btn-danger' data-bs-toggle='modal' data-bs-target='#excluirBebida'>remover</a>
                </td>
            </tr>
            ";
        }

        ?>

        
    </tbody>
</table>

<script>
    function abrirFoto(elemento){
        foto.setAttribute('src',elemento.getAttribute('data-image'));
    }
</script>

<!-- JavaScript Bundle with Popper -->

<!-- Modal -->
<div class="modal fade" id="abrirFoto" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
       
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <img width=100% alt="imagem aqui" id="foto"  src="">
      </div>
      
    </div>
  </div>
</div>

<!-- Modal de exclusão -->


<div class="modal fade" id="excluirBebida" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Exclusão De Categoria</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        Deseja Realmente Excluir esta Bebida ?
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
        <a class="btn btn-danger btn-xs" href="/bebidas/excluir?id=<?=$cadaBebida->id;?>" data-toggle="modal"   data-target="#excluirCategoria">Excluir</a>
            
    </div>
    </div>
  </div>
</div>