<h1> Nova Categoria</h1>

<section class="row">
    <div class="col">
      <img width="90%" src="/img/add.svg" alt="">

    </div>

    <div class="col">
        <article class=" card card-body text-bg-dark">

        <form action="" method="post" enctype="multipart/form-data">
            <label for="name">Título</label>
                <input name="name" type="text" class="form-control mb-3">

               <div class="d-grid">
                     <button class="btn btn-outline-light btn-lg ">Salvar</button>
               </div>
        </form>

        </article>

    </div>
</section>