<h3 class="text-center mb-5">Edição de Categorias</h3>

<section class="row">
    <div class="col">
      <img width="60%" src="/../img/add.svg" alt="">

    </div>

    <div class="col">
        <article class=" card card-body text-bg-dark">

        <form action="" method="post" enctype="multipart/form-data">

            <?php
                foreach($categories as $cat){
                                  
                }
            ?>
            
            <label for="name">Titulo</label>
                <input value="<?=$cat->name;?>"  name="name" type="text" class="form-control mb-3"">
        

               <div class="d-grid">
                     <button class="btn btn-outline-light btn-lg ">Salvar</button>
               </div>

        </form>

        </article>

    </div>
</section>